In [52]:
import pandas as pd

df = pd.read_parquet("data/processed/supply_chain_clean.parquet")
df.shape

(172765, 36)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 172765 entries, 1 to 180519
Data columns (total 36 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   payment_type                 172765 non-null  object
 1   days_for_shipment_scheduled  172765 non-null  int64
 2   benefit_per_order            172765 non-null  float64
 3   sales_per_customer           172765 non-null  float64
 4   late_delivery_risk           172765 non-null  int64
 5   category_name                172765 non-null  object
 6   customer_city                172765 non-null  object
 7   customer_country             172765 non-null  object
 8   customer_segment             172765 non-null  object
 9   customer_state               172765 non-null  object
 10  department_id                172765 non-null  int64
 11  department_name              172765 non-null  object
 12  latitude                     172765 non-null  float64
 13  longitude                    172765 non-null  float64
 14  market                       172765 non-null  object
 15  order_city                   172765 non-null  object
 16  order_country                172765 non-null  object
 17  order_customer_id            172765 non-null  int64
 18  order_date                   172765 non-null  datetime64[ns]
 19  order_item_discount          172765 non-null  float64
 20  order_item_discount_rate     172765 non-null  float64
 21  order_item_product_price     172765 non-null  float64
 22  order_item_profit_ratio      172765 non-null  float64
 23  order_item_quantity          172765 non-null  int64
 24  sales                        172765 non-null  float64
 25  order_item_total             172765 non-null  float64
 26  order_profit_per_order       172765 non-null  float64
 27  order_region                 172765 non-null  object
 28  order_state                  172765 non-null  object
 29  order_status                 172765 non-null  object
 30  product_category_id          172765 non-null  int64
 31  product_name                 172765 non-null  object
 32  product_price                172765 non-null  float64
 33  product_status               172765 non-null  int64
 34  shipping_date                172765 non-null  datetime64[ns]
 35  shipping_mode                172765 non-null  object
dtypes: datetime64[ns](2), float64(12), int64(7), object(15)
memory usage: 48.8+ MB

In [54]:
df['shipping_mode']=df['shipping_mode'].astype('category')
df['payment_type']=df['payment_type'].astype('category')
df['customer_segment']=df['customer_segment'].astype('category')
df['market']=df['market'].astype('category')

In [55]:
df.head()

,payment_type,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,late_delivery_risk,category_name,customer_city,customer_country,customer_segment,customer_state,...,order_profit_per_order,order_region,order_state,order_status,product_category_id,product_name,product_price,product_status,shipping_date,shipping_mode
order_item_id,,,,,,,,,,,,,,,,,,,,,
1,CASH,4,88.790001,239.979996,0,Camping & Hiking,Hickory,EE. UU.,Consumer,NC,...,88.790001,Central America,Distrito Federal,CLOSED,43,Diamondback Women's Serene Classic Comfort Bi,299.980011,0,2015-01-03 00:00:00,Standard Class
2,PAYMENT,4,91.180000,193.990005,0,Water Sports,Chicago,EE. UU.,Consumer,IL,...,91.180000,South America,Risaralda,PENDING_PAYMENT,48,Pelican Sunstream 100 Kayak,199.990005,0,2015-01-04 00:21:00,Standard Class
3,PAYMENT,4,68.250000,227.500000,0,Women's Apparel,Chicago,EE. UU.,Consumer,IL,...,68.250000,South America,Risaralda,PENDING_PAYMENT,24,Nike Men's Dri-FIT Victory Golf Polo,50.000000,0,2015-01-04 00:21:00,Standard Class
4,PAYMENT,4,36.470001,107.889999,0,Men's Footwear,Chicago,EE. UU.,Consumer,IL,...,36.470001,South America,Risaralda,PENDING_PAYMENT,18,Nike Men's CJ Elite 2 TD Football Cleat,129.990005,0,2015-01-04 00:21:00,Standard Class
5,CASH,4,4.100000,40.980000,1,Accessories,San Antonio,EE. UU.,Home Office,TX,...,4.100000,South America,Risaralda,CLOSED,40,Team Golf New England Patriots Putter Grip,24.990000,0,2015-01-06 01:03:00,Standard Class

In [56]:
df.isna().sum().sort_values(ascending=False)

payment_type                   0
days_for_shipment_scheduled    0
order_item_discount_rate       0
order_item_product_price       0
order_item_profit_ratio        0
order_item_quantity            0
sales                          0
order_item_total               0
order_profit_per_order         0
order_region                   0
order_state                    0
order_status                   0
product_category_id            0
product_name                   0
product_price                  0
product_status                 0
shipping_date                  0
order_item_discount            0
order_date                     0
order_customer_id              0
customer_segment               0
benefit_per_order              0
sales_per_customer             0
late_delivery_risk             0
category_name                  0
customer_city                  0
customer_country               0
customer_state                 0
order_country                  0
department_id                  0
department_name                0
latitude                       0
longitude                      0
market                         0
order_city                     0
shipping_mode                  0
dtype: int64

In [57]:
df['late_delivery_risk'].value_counts()

late_delivery_risk
1    98977
0    73788
Name: count, dtype: int64

In [58]:
df.select_dtypes(include='object').nunique().sort_values(ascending=False)

order_city          3585
order_state         1083
customer_city        563
order_country        164
product_name         118
category_name         50
customer_state        46
order_region          23
department_name       11
order_status           7
customer_country       2
dtype: int64

In [59]:
df.groupby('order_status')['late_delivery_risk'].mean().sort_values(ascending=False)

order_status
PENDING            0.579028
PENDING_PAYMENT    0.575467
COMPLETE           0.574860
PAYMENT_REVIEW     0.571580
PROCESSING         0.570861
CLOSED             0.566323
ON_HOLD            0.555896
Name: late_delivery_risk, dtype: float64

In [71]:
categorical_features = [
    'shipping_mode', 'payment_type', 'customer_segment',
    'market', 'department_name', 'order_region',
    'category_name', 'order_status'
]

for col in categorical_features:
    print(df.groupby(col, observed=True)['late_delivery_risk'].mean().sort_values(ascending=False))
    print()

shipping_mode
First Class       1.000000
Second Class      0.798290
Same Day          0.479285
Standard Class    0.397691
Name: late_delivery_risk, dtype: float64

payment_type
PAYMENT     0.575291
TRANSFER    0.574782
DEBIT       0.572177
CASH        0.566323
Name: late_delivery_risk, dtype: float64

customer_segment
Home Office    0.575883
Consumer       0.573116
Corporate      0.570781
Name: late_delivery_risk, dtype: float64

market
Europe          0.576897
USCA            0.574085
Pacific Asia    0.573753
LATAM           0.568740
Africa          0.568406
Name: late_delivery_risk, dtype: float64

department_name
Pet Shop              0.614407
Book Shop             0.585678
Health and Beauty     0.583815
Fitness               0.580034
Outdoors              0.580015
Technology            0.577364
Golf                  0.572841
Footwear              0.572241
Apparel               0.572157
Fan Shop              0.571939
Discs Shop            0.567679
Name: late_delivery_risk, dtype: float64

order_region
Central Africa     0.601485
Western Europe     0.585302
South of  USA      0.585214
South Asia         0.583501
East Africa        0.581696
East of USA        0.581684
Southeast Asia     0.579794
West Asia          0.578141
Eastern Europe     0.576486
US Center          0.575270
South America      0.571842
Central America    0.571061
North Africa       0.570966
Southern Europe    0.567996
West of USA        0.567874
Eastern Asia       0.567188
Central Asia       0.564576
Oceania            0.563238
Northern Europe    0.562500
Southern Africa    0.560909
Caribbean          0.555276
West Africa        0.546906
Canada             0.515987
Name: late_delivery_risk, dtype: float64

category_name
Golf Bags & Carts       0.688525
Lacrosse                0.626140
Pet Supplies            0.614407
Cameras                 0.612100
Accessories             0.597525
Music                   0.594724
Fitness Accessories     0.594595
Boxing & MMA            0.592040
Crafts                  0.591703
As Seen on  TV!         0.590909
Sporting Goods          0.589286
Strength Training       0.587156
Books                   0.585678
Electronics             0.585317
Trade-In                0.585313
Golf Gloves             0.585034
Girls' Apparel          0.583993
Health and Beauty       0.583815
Tennis & Racquet        0.582803
Hunting & Shooting      0.582547
Consumer Electronics    0.581907
Women's Clothing        0.581616
Golf Shoes              0.579681
Garden                  0.579399
Basketball              0.578125
Shop By Sport           0.576129
Kids' Golf Clubs        0.575843
Baseball & Softball     0.574959
Toys                    0.573964
Cleats                  0.573956
Golf Balls              0.573770
Fishing                 0.573426
Water Sports            0.572379
Indoor/Outdoor Games    0.572009
Men's Clothing          0.570707
Women's Golf Clubs      0.570588
Women's Apparel         0.570491
Men's Footwear          0.570051
Cardio Equipment        0.569551
Camping & Hiking        0.569051
Video Games             0.565920
DVDs                    0.564270
Hockey                  0.559524
Children's Clothing     0.559486
Soccer                  0.551471
Baby                    0.550505
CDs                     0.536122
Golf Apparel            0.533800
Computers               0.527059
Men's Golf Clubs        0.492701
Name: late_delivery_risk, dtype: float64

order_status
PENDING            0.579028
PENDING_PAYMENT    0.575467
COMPLETE           0.574860
PAYMENT_REVIEW     0.571580
PROCESSING         0.570861
CLOSED             0.566323
ON_HOLD            0.555896
Name: late_delivery_risk, dtype: float64

In [61]:
df['shipping_mode'].value_counts()

shipping_mode
Standard Class    103153
Second Class       33806
First Class        26513
Same Day            9293
Name: count, dtype: int64

In [62]:
df.describe()

,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,late_delivery_risk,department_id,latitude,longitude,order_customer_id,order_date,order_item_discount,...,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,product_category_id,product_price,product_status,shipping_date
count,172765.000000,172765.000000,172765.000000,172765.000000,172765.000000,172765.000000,172765.000000,172765.000000,172765,172765.000000,...,172765.000000,172765.000000,172765.000000,172765.000000,172765.000000,172765.000000,172765.000000,172765.000000,172765.0,172765
mean,2.933100,22.032360,183.165948,0.572900,5.444095,29.724145,-84.912610,6687.759048,2016-06-12 15:25:39.457992192,20.662798,...,141.278595,0.120801,2.127694,203.828493,183.165948,22.032360,31.856065,141.278595,0.0,2016-06-16 03:25:14.452927232
min,0.000000,-4274.979980,7.490000,0.000000,2.000000,-33.937553,-158.025986,1.000000,2015-01-01 00:00:00,0.000000,...,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.979980,2.000000,9.990000,0.0,2015-01-03 00:00:00
25%,2.000000,7.030000,104.379997,0.000000,4.000000,18.265436,-98.443069,3252.000000,2015-09-21 18:01:00,5.400000,...,50.000000,0.080000,1.000000,119.980003,104.379997,7.030000,18.000000,50.000000,0.0,2015-09-25 08:59:00
50%,4.000000,31.520000,163.990005,1.000000,5.000000,33.144863,-76.847908,6457.000000,2016-06-11 08:11:00,14.000000,...,59.990002,0.270000,1.000000,199.919998,163.990005,31.520000,29.000000,59.990002,0.0,2016-06-15 03:38:00
75%,4.000000,64.800003,247.399994,1.000000,7.000000,39.279617,-66.370583,9782.000000,2017-02-28 21:08:00,29.990000,...,199.990005,0.360000,3.000000,299.950012,247.399994,64.800003,45.000000,199.990005,0.0,2017-03-04 08:00:00
max,4.000000,911.799988,1939.989990,1.000000,12.000000,48.781933,115.263077,20757.000000,2018-01-31 23:38:00,500.000000,...,1999.989990,0.500000,5.000000,1999.989990,1939.989990,911.799988,76.000000,1999.989990,0.0,2018-02-06 22:14:00
std,1.373405,104.355313,120.141871,0.494659,1.629248,9.811816,21.410511,4165.069180,NaN,21.818601,...,139.862956,0.466610,1.453663,132.392520,120.141871,104.355313,15.642216,139.862956,0.0,NaN

In [63]:
df[ df['product_price'] < 0 ]

Empty DataFrame
Columns: [payment_type, days_for_shipment_scheduled, benefit_per_order, sales_per_customer, late_delivery_risk, category_name, customer_city, customer_country, customer_segment, customer_state, department_id, department_name, latitude, longitude, market, order_city, order_country, order_customer_id, order_date, order_item_discount, order_item_discount_rate, order_item_product_price, order_item_profit_ratio, order_item_quantity, sales, order_item_total, order_profit_per_order, order_region, order_state, order_status, product_category_id, product_name, product_price, product_status, shipping_date, shipping_mode]
Index: []

[0 rows x 36 columns]

In [64]:
df[ df['order_item_discount_rate'] > 1 ]

Empty DataFrame
Columns: [payment_type, days_for_shipment_scheduled, benefit_per_order, sales_per_customer, late_delivery_risk, category_name, customer_city, customer_country, customer_segment, customer_state, department_id, department_name, latitude, longitude, market, order_city, order_country, order_customer_id, order_date, order_item_discount, order_item_discount_rate, order_item_product_price, order_item_profit_ratio, order_item_quantity, sales, order_item_total, order_profit_per_order, order_region, order_state, order_status, product_category_id, product_name, product_price, product_status, shipping_date, shipping_mode]
Index: []

[0 rows x 36 columns]

In [65]:
df['product_price'].equals(df['order_item_product_price'])

True

In [66]:
df.groupby('shipping_mode', observed=True)['days_for_shipment_scheduled'].describe()

                   count  mean  std  min  25%  50%  75%  max
shipping_mode
First Class      26513.0   1.0  0.0  1.0  1.0  1.0  1.0  1.0
Same Day          9293.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0
Second Class     33806.0   2.0  0.0  2.0  2.0  2.0  2.0  2.0
Standard Class  103153.0   4.0  0.0  4.0  4.0  4.0  4.0  4.0

In [67]:
df.groupby('shipping_mode', observed=True)['order_item_quantity'].describe()

                   count      mean       std  min  25%  50%  75%  max
shipping_mode
First Class      26513.0  2.132312  1.457840  1.0  1.0  1.0  3.0  5.0
Same Day          9293.0  2.148929  1.459449  1.0  1.0  1.0  3.0  5.0
Second Class     33806.0  2.125362  1.454987  1.0  1.0  1.0  3.0  5.0
Standard Class  103153.0  2.125357  1.451634  1.0  1.0  1.0  3.0  5.0

In [68]:
df['benefit_per_order'].equals(df['order_profit_per_order'])

True

In [69]:
df['sales_per_customer'].equals(df['order_item_total'])

True

In [70]:
df.to_parquet("data/processed/supply_chain_eda.parquet")