In [5]:
import pandas as pd

df = pd.read_parquet("data/processed/supply_chain_eda.parquet")
df.shape

(172765, 36)

In [6]:
df = df.drop(columns=['order_item_product_price', 'benefit_per_order', 'sales_per_customer', 'days_for_shipment_scheduled'])

In [7]:
df.shape

(172765, 32)

In [8]:
df[df['order_date']>df['shipping_date']]

Empty DataFrame
Columns: [payment_type, late_delivery_risk, category_name, customer_city, customer_country, customer_segment, customer_state, department_id, department_name, latitude, longitude, market, order_city, order_country, order_customer_id, order_date, order_item_discount, order_item_discount_rate, order_item_profit_ratio, order_item_quantity, sales, order_item_total, order_profit_per_order, order_region, order_state, order_status, product_category_id, product_name, product_price, product_status, shipping_date, shipping_mode]
Index: []

[0 rows x 32 columns]

In [9]:
df['order_weekday']= df['order_date'].dt.weekday
df['order_date_month']=df['order_date'].dt.month

In [10]:
df[['order_date', 'order_weekday', 'order_date_month']].head()

                       order_date  order_weekday  order_date_month
order_item_id
1             2015-01-01 00:00:00              3                 1
2             2015-01-01 00:21:00              3                 1
3             2015-01-01 00:21:00              3                 1
4             2015-01-01 00:21:00              3                 1
5             2015-01-01 01:03:00              3                 1

In [11]:
df.groupby('department_name')['department_id'].describe()

                      count  mean  std   min   25%   50%   75%   max
department_name
Apparel             46884.0   4.0  0.0   4.0   4.0   4.0   4.0   4.0
Book Shop             391.0   8.0  0.0   8.0   8.0   8.0   8.0   8.0
Discs Shop           1943.0   9.0  0.0   9.0   9.0   9.0   9.0   9.0
Fan Shop            64033.0   7.0  0.0   7.0   7.0   7.0   7.0   7.0
Fitness              2374.0   2.0  0.0   2.0   2.0   2.0   2.0   2.0
Footwear            13891.0   3.0  0.0   3.0   3.0   3.0   3.0   3.0
Golf                31768.0   5.0  0.0   5.0   5.0   5.0   5.0   5.0
Health and Beauty     346.0  12.0  0.0  12.0  12.0  12.0  12.0  12.0
Outdoors             9267.0   6.0  0.0   6.0   6.0   6.0   6.0   6.0
Pet Shop              472.0  11.0  0.0  11.0  11.0  11.0  11.0  11.0
Technology           1396.0  10.0  0.0  10.0  10.0  10.0  10.0  10.0

In [12]:
df.groupby('category_name')['product_category_id'].nunique()

category_name
Accessories             1
As Seen on  TV!         1
Baby                    1
Baseball & Softball     1
Basketball              1
Books                   1
Boxing & MMA            1
CDs                     1
Cameras                 1
Camping & Hiking        1
Cardio Equipment        1
Children's Clothing     1
Cleats                  1
Computers               1
Consumer Electronics    1
Crafts                  1
DVDs                    1
Electronics             2
Fishing                 1
Fitness Accessories     1
Garden                  1
Girls' Apparel          1
Golf Apparel            1
Golf Bags & Carts       1
Golf Balls              1
Golf Gloves             1
Golf Shoes              1
Health and Beauty       1
Hockey                  1
Hunting & Shooting      1
Indoor/Outdoor Games    1
Kids' Golf Clubs        1
Lacrosse                1
Men's Clothing          1
Men's Footwear          1
Men's Golf Clubs        1
Music                   1
Pet Supplies            1
Shop By Sport           1
Soccer                  1
Sporting Goods          1
Strength Training       1
Tennis & Racquet        1
Toys                    1
Trade-In                1
Video Games             1
Water Sports            1
Women's Apparel         1
Women's Clothing        1
Women's Golf Clubs      1
Name: product_category_id, dtype: int64

In [13]:
df[df['product_category_id'].isin([13, 37])].groupby('product_category_id')['department_name'].describe()

                    count unique       top  freq
product_category_id
13                   1070      1  Footwear  1070
37                   1954      1  Outdoors  1954

In [14]:
df['category_label'] = df['category_name']
mask = df['category_name'] == 'Electronics'
df.loc[mask, 'category_label'] = 'Electronics (' + df.loc[mask, 'department_name'] + ')'

In [15]:
df[df['category_name'] == 'Electronics']['category_label'].value_counts()

category_label
Electronics (Outdoors)    1954
Electronics (Footwear)    1070
Name: count, dtype: int64

In [16]:
df.groupby('category_label')['product_category_id'].describe()

                          count  mean  std   min   25%   50%   75%   max
category_label
Accessories              1697.0  40.0  0.0  40.0  40.0  40.0  40.0  40.0
As Seen on  TV!            66.0  16.0  0.0  16.0  16.0  16.0  16.0  16.0
Baby                      198.0  60.0  0.0  60.0  60.0  60.0  60.0  60.0
Baseball & Softball       607.0   3.0  0.0   3.0   3.0   3.0   3.0   3.0
Basketball                 64.0   4.0  0.0   4.0   4.0   4.0   4.0   4.0
Books                     391.0  59.0  0.0  59.0  59.0  59.0  59.0  59.0
Boxing & MMA              402.0  12.0  0.0  12.0  12.0  12.0  12.0  12.0
CDs                       263.0  61.0  0.0  61.0  61.0  61.0  61.0  61.0
Cameras                   562.0  62.0  0.0  62.0  62.0  62.0  62.0  62.0
Camping & Hiking        13157.0  43.0  0.0  43.0  43.0  43.0  43.0  43.0
Cardio Equipment        11948.0   9.0  0.0   9.0   9.0   9.0   9.0   9.0
Children's Clothing       622.0  63.0  0.0  63.0  63.0  63.0  63.0  63.0
Cleats                  23514.0  17.0  0.0  17.0  17.0  17.0  17.0  17.0
Computers                 425.0  64.0  0.0  64.0  64.0  64.0  64.0  64.0
Consumer Electronics      409.0  65.0  0.0  65.0  65.0  65.0  65.0  65.0
Crafts                    458.0  66.0  0.0  66.0  66.0  66.0  66.0  66.0
DVDs                      459.0  67.0  0.0  67.0  67.0  67.0  67.0  67.0
Electronics (Footwear)   1070.0  13.0  0.0  13.0  13.0  13.0  13.0  13.0
Electronics (Outdoors)   1954.0  37.0  0.0  37.0  37.0  37.0  37.0  37.0
Fishing                 16595.0  45.0  0.0  45.0  45.0  45.0  45.0  45.0
Fitness Accessories       296.0  11.0  0.0  11.0  11.0  11.0  11.0  11.0
Garden                    466.0  68.0  0.0  68.0  68.0  68.0  68.0  68.0
Girls' Apparel           1137.0  26.0  0.0  26.0  26.0  26.0  26.0  26.0
Golf Apparel              429.0  32.0  0.0  32.0  32.0  32.0  32.0  32.0
Golf Bags & Carts          61.0  34.0  0.0  34.0  34.0  34.0  34.0  34.0
Golf Balls               1403.0  36.0  0.0  36.0  36.0  36.0  36.0  36.0
Golf Gloves              1029.0  35.0  0.0  35.0  35.0  35.0  35.0  35.0
Golf Shoes                502.0  33.0  0.0  33.0  33.0  33.0  33.0  33.0
Health and Beauty         346.0  69.0  0.0  69.0  69.0  69.0  69.0  69.0
Hockey                    588.0   7.0  0.0   7.0   7.0   7.0   7.0   7.0
Hunting & Shooting        424.0  44.0  0.0  44.0  44.0  44.0  44.0  44.0
Indoor/Outdoor Games    18470.0  46.0  0.0  46.0  46.0  46.0  46.0  46.0
Kids' Golf Clubs          356.0  38.0  0.0  38.0  38.0  38.0  38.0  38.0
Lacrosse                  329.0   5.0  0.0   5.0   5.0   5.0   5.0   5.0
Men's Clothing            198.0  70.0  0.0  70.0  70.0  70.0  70.0  70.0
Men's Footwear          21263.0  18.0  0.0  18.0  18.0  18.0  18.0  18.0
Men's Golf Clubs          274.0  30.0  0.0  30.0  30.0  30.0  30.0  30.0
Music                     417.0  71.0  0.0  71.0  71.0  71.0  71.0  71.0
Pet Supplies              472.0  72.0  0.0  72.0  72.0  72.0  72.0  72.0
Shop By Sport           10515.0  29.0  0.0  29.0  29.0  29.0  29.0  29.0
Soccer                    136.0   2.0  0.0   2.0   2.0   2.0   2.0   2.0
Sporting Goods            336.0  73.0  0.0  73.0  73.0  73.0  73.0  73.0
Strength Training         109.0  10.0  0.0  10.0  10.0  10.0  10.0  10.0
Tennis & Racquet          314.0   6.0  0.0   6.0   6.0   6.0   6.0   6.0
Toys                      507.0  74.0  0.0  74.0  74.0  74.0  74.0  74.0
Trade-In                  926.0  41.0  0.0  41.0  41.0  41.0  41.0  41.0
Video Games               804.0  75.0  0.0  75.0  75.0  75.0  75.0  75.0
Water Sports            14880.0  48.0  0.0  48.0  48.0  48.0  48.0  48.0
Women's Apparel         20116.0  24.0  0.0  24.0  24.0  24.0  24.0  24.0
Women's Clothing          631.0  76.0  0.0  76.0  76.0  76.0  76.0  76.0
Women's Golf Clubs        170.0  31.0  0.0  31.0  31.0  31.0  31.0  31.0

In [17]:
df.nunique()

payment_type                    4
late_delivery_risk              2
category_name                  50
customer_city                 563
customer_country                2
customer_segment                3
customer_state                 46
department_id                  11
department_name                11
latitude                    11102
longitude                    4476
market                          5
order_city                   3585
order_country                 164
order_customer_id           20261
order_date                  62897
order_item_discount          1014
order_item_discount_rate       18
order_item_profit_ratio       162
order_item_quantity             5
sales                         193
order_item_total             2913
order_profit_per_order      21678
order_region                   23
order_state                  1083
order_status                    7
product_category_id            51
product_name                  118
product_price                  75
product_status                  1
shipping_date               61024
shipping_mode                   4
order_weekday                   7
order_date_month               12
category_label                 51
dtype: int64

In [18]:
df.drop(columns='product_status', inplace = True)

In [20]:
df.to_parquet("data/processed/supply_chain_fe.parquet")